### ISSUE TITLE
Applying a height map sized from a gcode gives an error

### ISSUE THREAD

**Issue by classbproject** [martin2250/OpenCNCPilot#72] opened 2018-10-13 07:16 UTC
Hi, today I opened a gcode file and then created a heightmap sized to this gcode by clicking on "Sized from gcode". The height map gets created properly however, when I try and apply this heightmap I get the following error. 

![](https://i.imgur.com/2Fv6Ogv.png)

The gcode is available [here](https://pastebin.com/gFcgHRQG).

I saved the heightmap and that is available [here](https://pastebin.com/KaEjpPL1).

Altering the heightmap manually to envelop the whole toolpath works but when its sized from the gcode, isn't it supposed to do that automatically?

**Comment by martin2250** [comment] 2018-10-15 15:49
Hi, this is probably caused by rounding errors. IIRC OpenCNCPilot uses 3 decimal places for displaying numbers, your code uses 4. I'll change the dialog to use the floor/ceiling functions instead of rounding.

**Comment by classbproject** [comment] 2018-10-15 16:09
I see. Ok. Let me know if you want me to close this issue since it has a solution but a manual one.

**Comment by martin2250** [comment] 2018-10-15 18:02
Nah, leave it open. I'll close it when I've changed the code.

**Closed as completed** 2018-11-01 09:14 UTC
